#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msal-extensions
Version  : 0.2.2
Release  : 6
URL      : https://files.pythonhosted.org/packages/c5/af/8f05a701fecb570327fd2ba580120671722a099a464af180ccb20f1305f2/msal-extensions-0.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/c5/af/8f05a701fecb570327fd2ba580120671722a099a464af180ccb20f1305f2/msal-extensions-0.2.2.tar.gz
Summary  : UNKNOWN
Group    : Development/Tools
License  : MIT
Requires: msal-extensions-python = %{version}-%{release}
Requires: msal-extensions-python3 = %{version}-%{release}
Requires: msal
Requires: pathlib2
Requires: portalocker
BuildRequires : buildreq-distutils3
BuildRequires : msal
BuildRequires : pathlib2
BuildRequires : portalocker

%description
# Microsoft Authentication Extensions for Python

%package python
Summary: python components for the msal-extensions package.
Group: Default
Requires: msal-extensions-python3 = %{version}-%{release}

%description python
python components for the msal-extensions package.


%package python3
Summary: python3 components for the msal-extensions package.
Group: Default
Requires: python3-core
Provides: pypi(msal_extensions)
Requires: pypi(msal)
Requires: pypi(portalocker)

%description python3
python3 components for the msal-extensions package.


%prep
%setup -q -n msal-extensions-0.2.2
cd %{_builddir}/msal-extensions-0.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588881376
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
